name: Publish .NET
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rid: [win, linux, osx]
        arch: [x64, arm64]
        include:
          - rid: linux
            os: ubuntu-latest
          - rid: win
            os: windows-latest
          - rid: osx
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet publish -r ${{ matrix.rid }}-${{ matrix.arch }}
